export enum StationsEnum {
  FRANCEINTER = 'FRANCEINTER',
  FRANCEINFO = 'FRANCEINFO',
  FRANCEBLEU = 'FRANCEBLEU',
  FRANCEMUSIQUE = 'FRANCEMUSIQUE',
  FRANCECULTURE = 'FRANCECULTURE',
  MOUV = "MOUV",
  FIP = 'FIP'
}
